services:
  cloud-db:
    image: postgres:15
    container_name: cloud-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cloud_db
    networks:
      - cloud-network

  master-node:
    build: ./master_node
    container_name: master-node
    ports:
      - "8000:8000"
    depends_on:
      - cloud-db
    networks:
      - cloud-network

  worker-1:
    build: ./worker_node
    container_name: worker-1
    ports:
      - "8001:8001" # Porta exposta para testar o Worker de forma isolada
    networks:
      - cloud-network

networks:
  cloud-network:
    driver: bridge
