services:
  cloud-db:
    image: postgres:15
    container_name: cloud-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cloud_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d cloud_db"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - cloud-network
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  master-node:
    build: ./master_node
    container_name: master-node
    ports:
      - "8000:8000"
    depends_on:
      cloud-db:
        condition: service_healthy
    networks:
      - cloud-network
    environment:
      #- DOCKER_HOST=tcp://host.docker.internal:2375
      - DATABASE_URL=postgresql+psycopg2://user:password@cloud-db:5432/cloud_db
      - WORKER_IMAGE=mini-cloud-worker:latest
      - WORKER_NETWORK=mini-cloud-project_cloud-network
      - MIN_WORKERS=1
      - MAX_WORKERS=5
      - SCALE_UP_THRESHOLD=60
      - SCALE_DOWN_THRESHOLD=20
      - COOLDOWN_SECONDS=30
    volumes:
      - storage_primary:/data/storage
      - storage_replica:/data/storage_replica
      - /var/run/docker.sock:/var/run/docker.sock

  worker-1:
    build: ./worker_node
    image: mini-cloud-worker:latest
    container_name: worker-1
    labels:
      - "role=worker"
    ports:
      - "8001:8001"
    networks:
      - cloud-network
    volumes:
      - storage_primary:/data/storage

networks:
  cloud-network:
    driver: bridge

volumes:
  storage_primary:
  storage_replica: